client_config_backend: settings
client_config:
  client_id: your_client_id.apps.googleusercontent.com # change this
  client_secret: your_client_secret # change this

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
