# This is a basic workflow to help you get started with Actions

name: linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-python:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run black
        run: |
        python -m pip install black
        black ./src/

  lint-md:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2

      - name: Run MD lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          # files, directories, or globs
          files: .
          config_file: .github/rules/md-rules.json

      - name: Validate MD links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:
          use-verbose-mode: yes