name: linting

on:
  push:

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install black
      - name: Run black
        run: python3 -m black --check ./src/

  md-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run MD lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .github/rules/md-rules.json

      - name: Validate MD links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
        with:
          use-verbose-mode: yes

  cpplinter:
    name: cpp linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: cpplint
        run: |
          pip install cpplint
          cpplint --recursive --root=./src/node_src --filter=-build/include_subdir,-legal/copyright --exclude=./src/node_src/build ./src/node_src/
  cppchecker:
    name: cpp code checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        run: |
          sudo apt-get install cppcheck
          cppcheck --enable=all --inline-suppr --suppress=missingInclude --suppress=unusedFunction src/node_src/ -i src/node_src/build/ --error-exitcode=1
