name: linting

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run black
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install wheel
          python3 -m pip install black
          python3 -m black --check ./src/